// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnAO887F3KDr6WRSZ79MwZOpUwXD24rmM',
    appId: '1:518323966946:web:09e530d40782aa2f41dfbb',
    messagingSenderId: '518323966946',
    projectId: 'chat--box',
    authDomain: 'chat--box.firebaseapp.com',
    storageBucket: 'chat--box.appspot.com',
    measurementId: 'G-86GV31RVQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFPvJR9tI75F__SXX3ip6bvjqQf5noDk',
    appId: '1:518323966946:android:4e52d02cf129e52b41dfbb',
    messagingSenderId: '518323966946',
    projectId: 'chat--box',
    storageBucket: 'chat--box.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdv1KnH18wxUUZI_2KBibr4DBd34KCTs',
    appId: '1:518323966946:ios:c9a58c37e91b152941dfbb',
    messagingSenderId: '518323966946',
    projectId: 'chat--box',
    storageBucket: 'chat--box.appspot.com',
    iosClientId: '518323966946-ahi67vntvdr9unll1f48c41admjgt01l.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );
}
